[project]
name = "HyCoRec"
version = "0.1.0"
description = "The implementation of HyCoRec: Hypergraph-Enhanced Multi-Preference Learning for Alleviating Matthew Effect in Conversational Recommendation (ACL 2024)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "ijson>=3.5.1",
    "loguru>=0.7.3",
    "nltk>=3.9.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
    "torch-geometric>=2.6.1",
    "tqdm>=4.67.1",
    "transformers>=4.55.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu129", marker = "sys_platform == 'linux'" },
]
dgl =[
  {index="dgl-cu129",  marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[dependency-groups]
dev = [
    "gdown>=6.1.0",
    "kaggle>=2.2.4",
    "kagglehub>=1.0.2",
    "matplotlib>=3.8",
    "ruff>=0.16.2",
]
